package my.noveldokusha.coreui.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Green Apple theme
 * Original color scheme by CarlosEsco, Jays2Kings and CrepeTF
 * M3 colors generated by Material Theme Builder
 */
internal object GreenAppleColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFF7ADB8F),
        onPrimary = Color(0xFF003917),
        primaryContainer = Color(0xFF005320),
        onPrimaryContainer = Color(0xFF80FF9A),
        secondary = Color(0xFF7ADB8F),
        onSecondary = Color(0xFF003917),
        secondaryContainer = Color(0xFF1E3A24),
        onSecondaryContainer = Color(0xFFB0E8B8),
        tertiary = Color(0xFFFFB3AC),
        onTertiary = Color(0xFF680008),
        tertiaryContainer = Color(0xFFC7282A),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF0F1510),
        onBackground = Color(0xFFDFE4DB),
        surface = Color(0xFF0F1510),
        onSurface = Color(0xFFDFE4DB),
        surfaceVariant = Color(0xFF3F493F),
        onSurfaceVariant = Color(0xFFBECABC),
        outline = Color(0xFF889487),
        outlineVariant = Color(0xFF3F493F),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFDFE4DB),
        inverseOnSurface = Color(0xFF2C322C),
        inversePrimary = Color(0xFF006D32),
        surfaceDim = Color(0xFF0F1510),
        surfaceBright = Color(0xFF353B35),
        surfaceContainerLowest = Color(0xFF0A0F0B),
        surfaceContainerLow = Color(0xFF181D18),
        surfaceContainer = Color(0xFF1C211C),
        surfaceContainerHigh = Color(0xFF262B26),
        surfaceContainerHighest = Color(0xFF313630),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF005927),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF80D890),
        onPrimaryContainer = Color(0xFF002A10),
        secondary = Color(0xFF005927),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE2F2E4),
        onSecondaryContainer = Color(0xFF002208),
        tertiary = Color(0xFF9D0012),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFD33131),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF6FBF2),
        onBackground = Color(0xFF181D18),
        surface = Color(0xFFF6FBF2),
        onSurface = Color(0xFF181D18),
        surfaceVariant = Color(0xFFDAE6D7),
        onSurfaceVariant = Color(0xFF3F493F),
        outline = Color(0xFF6F7A6E),
        outlineVariant = Color(0xFFBECABC),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF2C322C),
        inverseOnSurface = Color(0xFFEDF2E9),
        inversePrimary = Color(0xFF7ADB8F),
        surfaceDim = Color(0xFFD6DCD3),
        surfaceBright = Color(0xFFF6FBF2),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF0F5EC),
        surfaceContainer = Color(0xFFEAEFE6),
        surfaceContainerHigh = Color(0xFFE4EAE1),
        surfaceContainerHighest = Color(0xFFDFE4DB),
    )
    // -----------------------------------------------------------------------------------------
    // Reader colors — используются ТОЛЬКО в ReaderScreen
    // -----------------------------------------------------------------------------------------

    // Основной текст — нейтральный, без фиолетового оттенка темы
    override val readerTextColorDark: Color = Color(0xFFE8E8E8)  // тёплый почти-белый
    override val readerTextColorLight: Color = Color(0xFF1A1A1A) // мягкий почти-чёрный

    // Вторичный текст: номера глав, сноски, метаданные
    override val readerTextSecondaryColorDark: Color = Color(0xFFA0A0A0)
    override val readerTextSecondaryColorLight: Color = Color(0xFF5A5A5A)

    // Фон страницы чтения — совпадает с background, задан явно для будущего переопределения
    override val readerBackgroundColorDark: Color = Color(0xFF0F1510)
    override val readerBackgroundColorLight: Color = Color(0xFFF6FBF2)

    // Выделение текста — единственное место в ридере где допустим акцентный цвет
    override val readerSelectionColorDark: Color = Color(0x407ADB8F)
    override val readerSelectionColorLight: Color = Color(0x40005927)
}